import numpy as np
import unyt

kpc = 3.08567758e21
Msun = 1.9891e33
yr = 3.1556926e7
Myr = yr * 1e6
Zsolar = 0.0134 # Solar metallicity
mH_in_cgs = unyt.mh
mC_in_cgs = 12.0107 * unyt.mp
mN_in_cgs = 14.0067 * unyt.mp
mO_in_cgs = 15.999 * unyt.mp
mMg_in_cgs = 24.305 * unyt.mp
mFe_in_cgs = 55.845 * unyt.mp
mSi_in_cgs = 28.0855 * unyt.mp
mEu_in_cgs = 151.964 * unyt.mp
mBa_in_cgs = 137.327 * unyt.mp
mSr_in_cgs = 87.62 * unyt.mp
mNe_in_cgs = 20.1797 * unyt.mp
C_H_Sun_Asplund = 8.43 # Asplund et al. (2009)
N_H_Sun_Asplund = 7.83
O_H_Sun_Asplund = 8.69
Mg_H_Sun_Asplund = 7.6
Fe_H_Sun_Asplund = 7.5
Si_H_Sun_Asplund = 7.51
Eu_H_Sun_Asplund = 0.52
Ba_H_Sun_Asplund = 2.18
Sr_H_Sun_Asplund = 2.87
Ne_H_Sun_Asplund = 7.93
O_H_Sun = O_H_Sun_Asplund - 12.0 - np.log10(mH_in_cgs / mO_in_cgs)
Fe_H_Sun = Fe_H_Sun_Asplund - 12.0 - np.log10(mH_in_cgs / mFe_in_cgs)
Mg_H_Sun = Mg_H_Sun_Asplund - 12.0 - np.log10(mH_in_cgs / mMg_in_cgs)
C_Fe_Sun = C_H_Sun_Asplund - Fe_H_Sun_Asplund - np.log10(mFe_in_cgs / mC_in_cgs)
N_Fe_Sun = N_H_Sun_Asplund - Fe_H_Sun_Asplund - np.log10(mFe_in_cgs / mN_in_cgs)
O_Fe_Sun = O_H_Sun_Asplund - Fe_H_Sun_Asplund - np.log10(mFe_in_cgs / mO_in_cgs)
N_O_Sun = N_H_Sun_Asplund - O_H_Sun_Asplund - np.log10(mO_in_cgs / mN_in_cgs)
C_O_Sun = C_H_Sun_Asplund - O_H_Sun_Asplund - np.log10(mO_in_cgs / mC_in_cgs)
Mg_Fe_Sun = Mg_H_Sun_Asplund - Fe_H_Sun_Asplund - np.log10(mFe_in_cgs / mMg_in_cgs)
O_Mg_Sun = O_Fe_Sun - Mg_Fe_Sun
CN_Mg_Sun = 10 ** C_Fe_Sun + 10 ** N_Fe_Sun  # (C+N)/Fe
CN_Mg_Sun = np.log10(CN_Mg_Sun) - Mg_Fe_Sun  # [(C+N)/Fe] - [Mg/Fe] = [(C+N)/Mg]
Si_Fe_Sun = Si_H_Sun_Asplund - Fe_H_Sun_Asplund - np.log10(mFe_in_cgs / mSi_in_cgs)
Eu_Fe_Sun = Eu_H_Sun_Asplund - Fe_H_Sun_Asplund - np.log10(mFe_in_cgs / mEu_in_cgs)
Ba_Fe_Sun = Ba_H_Sun_Asplund - Fe_H_Sun_Asplund - np.log10(mFe_in_cgs / mBa_in_cgs)
Sr_Fe_Sun = Sr_H_Sun_Asplund - Fe_H_Sun_Asplund - np.log10(mFe_in_cgs / mSr_in_cgs)
Ne_Fe_Sun = Ne_H_Sun_Asplund - Fe_H_Sun_Asplund - np.log10(mFe_in_cgs / mNe_in_cgs)
Fe_over_H_Grevesse07 = 7.45 # solar ratios from Grevesse, Asplund & Sauval (2007)
Mg_over_H_Grevesse07 = 7.53
O_over_H_Grevesse07 = 8.66
C_over_H_Grevesse07 = 8.39
N_over_H_Grevesse07 = 7.78
Si_over_H_Grevesse07 = 7.51
Mg_over_Fe_Grevesse07 = Mg_over_H_Grevesse07 - Fe_over_H_Grevesse07
O_over_Fe_Grevesse07 = O_over_H_Grevesse07 - Fe_over_H_Grevesse07
C_over_Fe_Grevesse07 = C_over_H_Grevesse07 - Fe_over_H_Grevesse07
N_over_Fe_Grevesse07 = N_over_H_Grevesse07 - Fe_over_H_Grevesse07
Si_over_Fe_Grevesse07 = Si_over_H_Grevesse07 - Fe_over_H_Grevesse07
N_over_O_Grevesse07 = N_over_H_Grevesse07 - O_over_H_Grevesse07
C_over_O_Grevesse07 = C_over_H_Grevesse07 - O_over_H_Grevesse07
